version: "3"
services:
  web:
    container_name: node-api-brasilino
    build: .
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
  db:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_PASSWORD: root
    ports: 
      - "4000:5432"
    restart: always
